#This configuration file tells the Splunk Universal Forwarder to monitor the 2 files in Linux with relevant log data

# Monitor Linux for SSH, login, sudo, and authentication activity
[monitor:///var/log/auth.log]
disabled = false
index = linux
sourcetype = linux_secure

# Monitor Linux for general Linux system activity
[monitor:///var/log/syslog]
disabled = false
index = linux
sourcetype = syslog
